  #spring:
  #  datasource:
  ##    pooled: true
  #    driverClassName: com.mysql.cj.jdbc.Driver
  #    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  #
  #    url: jdbc:mysql://localhost:3306/job_hunter
  #    username: root
  #    password: 1234567
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
